export enum ConsumptionFrequencyEnum {
  NEVER = 'NEVER',
  LESS_THAN_ONE_PER_MONTH = 'LESS_THAN_ONE_PER_MONTH',
  ONCE_PER_MONTH = 'ONCE_PER_MONTH',
  ONCE_PER_WEEK = 'ONCE_PER_WEEK',
  MORE_THAN_ONCE_PER_WEEK = 'MORE_THAN_ONCE_PER_WEEK',
}
