export enum EmploymentStatusEnum {
  NOT_WORKING = 'NOT_WORKING',
  LESS_THAN_8_HOURS_WEEK = 'LESS_THAN_8_HOURS_WEEK',
  BETWEEN_8_AND_12_HOURS_WEEK = 'BETWEEN_8_AND_12_HOURS_WEEK',
  BETWEEN_12_AND_20_HOURS_WEEK = 'BETWEEN_12_AND_20_HOURS_WEEK',
  MORE_THAN_20_HOURS_WEEK = 'MORE_THAN_20_HOURS_WEEK',
}
