export enum PhysicalActivityEnum {
  NEVER = 'NEVER',
  ONE_TO_FOUR_HOURS_PER_WEEK = '1_TO_4_HOURS_PER_WEEK',
  FOUR_TO_SIX_HOURS_PER_WEEK = '4_TO_6_HOURS_PER_WEEK',
  SIX_TO_EIGHT_HOURS_PER_WEEK = '6_TO_8_HOURS_PER_WEEK',
  MORE_THAN_EIGHT_HOURS_PER_WEEK = 'MORE_THAN_8_HOURS_PER_WEEK',
}
